// Generated by CoffeeScript 1.4.0
var SelectionSorter;

SelectionSorter = (function() {

  if (typeof global !== "undefined" && global !== null) {
    module.exports = global.SelectionSorter = SelectionSorter;
  }

  function SelectionSorter() {}

  SelectionSorter.prototype.sort = function(nums) {
    this._sort(nums, 0, nums.length - 1);
    return nums;
  };

  SelectionSorter.prototype._sort = function(nums, low, high) {
    var i, indexOfMin, j, temp, _i, _j, _ref;
    for (i = _i = low; _i <= high; i = _i += 1) {
      indexOfMin = i;
      for (j = _j = _ref = i + 1; _j <= high; j = _j += 1) {
        if (nums[j] < nums[indexOfMin]) {
          indexOfMin = j;
        }
      }
      temp = nums[i];
      nums[i] = nums[indexOfMin];
      nums[indexOfMin] = temp;
    }
    return nums;
  };

  return SelectionSorter;

})();
